### ISSUE TITLE
I get always the same values from the sensor...

### ISSUE THREAD

**Issue by almoondsllc** [MikroElektronika/Air_Quality_5_click#1]
Hello, I ported the code to esp32 just rewriting the i2c read/write routine. When I run the code, I got always the same values like:

**** Airquality5 Sensor ******
NO2: 3160 NH3: 3416 CO: 3672 
**** Airquality5 Sensor ******
NO2: 3160 NH3: 3416 CO: 3672 
**** Airquality5 Sensor ******
NO2: 3160 NH3: 3416 CO: 3672 
**** Airquality5 Sensor ******
NO2: 3160 NH3: 3416 CO: 3672 

What should be an example of correct values for NO2, NH3, CO ? Are the three values expressed in ppm? Thanks

**Comment by almoondsllc** [comment]
Solved, 5V power was missing :)

**Comment by furkanhtk** [comment]
@almoondsllc Hi how you ported the code? Is there any chance to share it with me?
